env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'import'
rules: {
  "semi": ["error", "always"],
  "quotes": ["error", "double"],
  'no-console': 'off',
  'prefer-destructuring':'off',
  'no-param-reassign':'off',
  'max-len':'off',
}
